//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEPDAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Log_Report_DMS
    {
        public long Id { get; set; }
        public string ReportType { get; set; }
        public Nullable<int> Error_Records_Received { get; set; }
        public Nullable<int> Total_Records_Pushed { get; set; }
        public string Exception { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
