//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEPDAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLogBeforeSaveQuestion
    {
        public long Id { get; set; }
        public string MSPIN { get; set; }
        public Nullable<int> RandomLogicCount { get; set; }
        public Nullable<int> QuestionListCount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TotalQuestion { get; set; }
    }
}
