//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEPDAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLogWhile_AfterSavingQuestions
    {
        public long Id { get; set; }
        public string MSPIN { get; set; }
        public Nullable<int> QuestionCount { get; set; }
        public Nullable<int> ProcessedCount { get; set; }
        public Nullable<int> NotProcessed { get; set; }
        public string QuestionCode { get; set; }
        public string ExceptionMsg { get; set; }
        public Nullable<int> TotalQuestion { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> LineNumber { get; set; }
    }
}
