//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEPDAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudentAnswer
    {
        public int Id { get; set; }
        public Nullable<int> ProgramTestCalenderId { get; set; }
        public int ProgramId { get; set; }
        public Nullable<int> SA_Id { get; set; }
        public string MSPIN { get; set; }
        public string QuestionCode { get; set; }
        public string AnswerGiven { get; set; }
        public string CorrectAnswer { get; set; }
        public Nullable<int> Day { get; set; }
        public string TypeOfTest { get; set; }
        public string SessionID { get; set; }
        public Nullable<bool> IsAnswerCorrect { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
