//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUI.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.STEP_NominationSoap")]
    public interface STEP_NominationSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNominationFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNominationFile(int PNPMC, System.DateTime FromDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNominationFile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNominationFileAsync(int PNPMC, System.DateTime FromDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalendarFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCalendarFile(int PNPMC, System.DateTime FromDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalendarFile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCalendarFileAsync(int PNPMC, System.DateTime FromDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadAttendance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable UploadAttendance(System.Data.DataTable data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadAttendance", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> UploadAttendanceAsync(System.Data.DataTable data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadScore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable UploadScore(System.Data.DataTable data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadScore", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> UploadScoreAsync(System.Data.DataTable data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunBatchJob_Attendance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RunBatchJob_Attendance(string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunBatchJob_Attendance", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> RunBatchJob_AttendanceAsync(string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunBatchJob_Marks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RunBatchJob_Marks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunBatchJob_Marks", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> RunBatchJob_MarksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface STEP_NominationSoapChannel : ProjectUI.ServiceReference1.STEP_NominationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class STEP_NominationSoapClient : System.ServiceModel.ClientBase<ProjectUI.ServiceReference1.STEP_NominationSoap>, ProjectUI.ServiceReference1.STEP_NominationSoap {
        
        public STEP_NominationSoapClient() {
        }
        
        public STEP_NominationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public STEP_NominationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STEP_NominationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STEP_NominationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataTable GetNominationFile(int PNPMC, System.DateTime FromDate) {
            return base.Channel.GetNominationFile(PNPMC, FromDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNominationFileAsync(int PNPMC, System.DateTime FromDate) {
            return base.Channel.GetNominationFileAsync(PNPMC, FromDate);
        }
        
        public System.Data.DataTable GetCalendarFile(int PNPMC, System.DateTime FromDate) {
            return base.Channel.GetCalendarFile(PNPMC, FromDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCalendarFileAsync(int PNPMC, System.DateTime FromDate) {
            return base.Channel.GetCalendarFileAsync(PNPMC, FromDate);
        }
        
        public System.Data.DataTable UploadAttendance(System.Data.DataTable data) {
            return base.Channel.UploadAttendance(data);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> UploadAttendanceAsync(System.Data.DataTable data) {
            return base.Channel.UploadAttendanceAsync(data);
        }
        
        public System.Data.DataTable UploadScore(System.Data.DataTable data) {
            return base.Channel.UploadScore(data);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> UploadScoreAsync(System.Data.DataTable data) {
            return base.Channel.UploadScoreAsync(data);
        }
        
        public System.Data.DataTable RunBatchJob_Attendance(string EndDate) {
            return base.Channel.RunBatchJob_Attendance(EndDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> RunBatchJob_AttendanceAsync(string EndDate) {
            return base.Channel.RunBatchJob_AttendanceAsync(EndDate);
        }
        
        public System.Data.DataTable RunBatchJob_Marks() {
            return base.Channel.RunBatchJob_Marks();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> RunBatchJob_MarksAsync() {
            return base.Channel.RunBatchJob_MarksAsync();
        }
    }
}
